/* Un link per ogni prospect:  ?s=<chiave>
   kind: "estetica" | "parrucchiere" (colori e stile)
   menu (facoltativo): "barbiere" | "unghie" (listino su misura)
   city può restare vuota. */
window.SALONS = {
  // ---- Primo giro (email 8-9 ottobre) ----
  // Centri estetici
  barbara:  { name: "Salone Barbara",       kind: "estetica",     city: "Caldogno",     owner: "Barbara" },
  arte:     { name: "Estetica Artè",        kind: "estetica",     city: "Caldogno" },
  cynthia:  { name: "Cynthia Estetica",     kind: "estetica",     city: "Casalserugo",  owner: "Cynthia" },
  susycinzia: { name: "Susy e Cinzia",      kind: "estetica",     city: "Padova" },

  // Parrucchieri
  floriana: { name: "Floriana Parrucchieri", kind: "parrucchiere", city: "Bassano del Grappa", owner: "Floriana" },
  zoe:      { name: "Zoe Acconciature",      kind: "parrucchiere", city: "Padova" },
  niko:     { name: "Salone Niko",           kind: "parrucchiere", city: "Malo",       owner: "Niko" },
  trecento: { name: "Trecentosessantagradi", kind: "parrucchiere", city: "Malo" },
  claudio:  { name: "Salone Claudio",        kind: "parrucchiere", city: "Cassola",    owner: "Claudio" },
  sergio:   { name: "Beauty Fashion Gallery", kind: "parrucchiere", city: "Padova",    owner: "Sergio" },
  errelook: { name: "Errelook",              kind: "parrucchiere", city: "San Pietro in Gu", owner: "Raffaella" },
  leielui:  { name: "Centro Lei e Lui",      kind: "parrucchiere", city: "Rubano",     owner: "Mirco" },
  soins:    { name: "Soins",                 kind: "parrucchiere", city: "" },

  // ---- Secondo giro (WhatsApp 13-15 ottobre) ----
  // Centri estetici e unghie
  grazia:        { name: "ArteEstetica by Grazia",        kind: "estetica", city: "" },
  renaissance:   { name: "Estetica Renaissance",          kind: "estetica", city: "Bovolenta" },
  starbien:      { name: "Star Bien",                     kind: "estetica", city: "Bovolenta" },
  bottegaunghia: { name: "La Bottega dell'Unghia",        kind: "estetica", menu: "unghie", city: "Costabissara" },
  emysem:        { name: "Emysem Nails",                  kind: "estetica", menu: "unghie", city: "Vigonza" },
  esteticabarbara: { name: "Estetica Barbara",            kind: "estetica", city: "Vicenza" },
  essenza:       { name: "L'Essenza Estetica e Benessere", kind: "estetica", city: "" },
  lnnail:        { name: "L.N Nail",                      kind: "estetica", menu: "unghie", city: "" },
  solarium:      { name: "Centro Estetico Solarium",      kind: "estetica", city: "Pontelongo" },
  crystal:       { name: "Crystal Beauty",                kind: "estetica", city: "Rubano" },
  eternity:      { name: "Eternity Estetica e Benessere", kind: "estetica", city: "Rubano" },

  // Parrucchieri e barbieri
  barberia24:    { name: "Barberia 24",                   kind: "parrucchiere", menu: "barbiere", city: "" },
  sforbiciamo:   { name: "Sforbiciamo",                   kind: "parrucchiere", city: "" },
  artecapello:   { name: "L'Arte del Capello",            kind: "parrucchiere", city: "Bovolenta" },
  retual:        { name: "Retual",                        kind: "parrucchiere", city: "Bovolenta" },
  katia:         { name: "Katia Barberia",                kind: "parrucchiere", menu: "barbiere", city: "Casalserugo" },
  ded:           { name: "D&D Parrucchieri",              kind: "parrucchiere", city: "Maserà di Padova" },
  salonesara:    { name: "Salone Sara",                   kind: "parrucchiere", city: "Treschè Conca" },
  dacciuntaglio: { name: "Dacci un Taglio",               kind: "parrucchiere", menu: "barbiere", city: "" },
  bellicapelli:  { name: "BelliCapelli",                  kind: "parrucchiere", city: "" },
  bottega22:     { name: "Bottega 22",                    kind: "parrucchiere", city: "" },
  fan:           { name: "Fan Parrucchiere",              kind: "parrucchiere", city: "" },
  immagineline:  { name: "Immagine Line",                 kind: "parrucchiere", city: "" },
  cristina:      { name: "Salone Cristina",               kind: "parrucchiere", city: "" },
  angela:        { name: "Angela Hair Stylist",           kind: "parrucchiere", city: "Bertipaglia" },
  anila:         { name: "Anila · La Boutique del Capello", kind: "parrucchiere", city: "Casalserugo" },
  gianni:        { name: "Ambrosini Gianni",              kind: "parrucchiere", city: "Cesuna" },
  max:           { name: "Salone MAX",                    kind: "parrucchiere", menu: "barbiere", city: "Padova" },
  sografi:       { name: "Salone Sografi",                kind: "parrucchiere", city: "Padova" },
  bigodino:      { name: "Bigodino y Bigote",             kind: "parrucchiere", city: "Sandrigo" },
  oldbarbieri:   { name: "The Old Barbieri",              kind: "parrucchiere", menu: "barbiere", city: "Schio" },
  maurizio:      { name: "Salone Maurizio",               kind: "parrucchiere", city: "Vicenza" },

  // ---- Terzo giro: Alto Vicentino, priorità A (WhatsApp dal 12 ottobre) ----
  giuliaanddogs: { name: "Giulia And Dogs", kind: "toelettatura", city: "Chiuppano" },
  elisa: { name: "Estetica Elisa", kind: "estetica", city: "Zanè" },
  milobau: { name: "Milobau Toelettatura", kind: "toelettatura", city: "Zanè" },
  fisioterapiamedi: { name: "Fisioterapia Medica Devid", kind: "fisioterapia", city: "Chiuppano" },
  bellesserenieva: { name: "Estetica Bellessere Nieva", kind: "estetica", city: "Carrè" },
  alesstetika: { name: "Alesstetika", kind: "estetica", city: "Piovene Rocchette" },
  shanti: { name: "Shanti Estetica", kind: "estetica", city: "Piovene Rocchette" },
  mariaelenamattan: { name: "Maria Elena Mattana", kind: "parrucchiere", city: "Caltrano" },
  ricciololuilei: { name: "Il Ricciolo Lui e Lei", kind: "parrucchiere", city: "Caltrano" },
  sorgente: { name: "La Sorgente Centro Estetico", kind: "estetica", city: "Zanè" },
  nuovaimmagine: { name: "Nuova Immagine", kind: "parrucchiere", city: "Zanè" },
  karisma: { name: "Karisma", kind: "estetica", city: "Lugo di Vicenza" },
  emozionibellezza: { name: "Emozioni di Bellezza", kind: "estetica", city: "Thiene" },
  paolagiorgia: { name: "Estetica Paola e Giorgia", kind: "estetica", city: "Thiene" },
  liberamente: { name: "Liberamente Estetica", kind: "estetica", city: "Thiene" },
  bottegaroberta: { name: "La Bottega Estetica di Roberta", kind: "estetica", city: "Schio" },
  sonia: { name: "Estetica Sonia", kind: "estetica", city: "Schio" },
  laura: { name: "Estetica L'Aura", kind: "estetica", city: "Schio" },
  fisioup: { name: "FisioUp", kind: "fisioterapia", city: "Schio" },
  andreazimoli: { name: "Studio Andrea Zimoli", kind: "fisioterapia", city: "Schio" },
  beautyconsulting: { name: "Beauty Consulting", kind: "estetica", city: "Schio" },
  elitefisiosport: { name: "Elite Fisiosport", kind: "fisioterapia", city: "Schio" },
  federica: { name: "Salone Federica", kind: "estetica", city: "Schio" },
  primaluce: { name: "Prima Luce Centro Estetico", kind: "estetica", city: "Sarcedo" },
  ren: { name: "Ren", kind: "fisioterapia", city: "Sarcedo" },
  newage: { name: "New Age", kind: "parrucchiere", menu: "barbiere", city: "Zanè" },
  ideacatdog: { name: "Idea Cat & Dog", kind: "toelettatura", city: "Sarcedo" },
  danielaborgo: { name: "Daniela Borgo", kind: "estetica", city: "Chiuppano" },
  stefania: { name: "Estetica Stefania", kind: "estetica", city: "Carrè" },
  naturalbeauty: { name: "Natural Beauty", kind: "estetica", city: "Carrè" },
  limbios: { name: "Estetica Limbios", kind: "estetica", city: "Piovene Rocchette" },
  mariapatriziasec: { name: "Maria Patrizia Seccia", kind: "estetica", city: "Piovene Rocchette" },
  roberta: { name: "Estetica Roberta", kind: "estetica", city: "Piovene Rocchette" },
  elemiss: { name: "Elemiss", kind: "estetica", city: "Zanè" },
  sacrumcor: { name: "Sacrum Cor Tatuaggi", kind: "tatuaggi", city: "Zanè" },
  babylon: { name: "Centro Estetico Babylon", kind: "estetica", city: "Santorso" },
  phisys: { name: "Phisys", kind: "fisioterapia", city: "Lugo di Vicenza" },
  newlook: { name: "New Look Salone", kind: "parrucchiere", city: "Marano Vicentino" },
  fashion: { name: "Salone Fashion", kind: "parrucchiere", city: "Marano Vicentino" },
  tao: { name: "Estetica Tao", kind: "estetica", city: "Thiene" },
  emperial: { name: "Emperial", kind: "estetica", city: "Thiene" },
  cocobeaute: { name: "Coco Beauté", kind: "estetica", city: "Thiene" },
  suavis: { name: "Estetica Suavis", kind: "estetica", city: "Thiene" },
  riccicapricci: { name: "Ricci & Capricci", kind: "parrucchiere", city: "Thiene" },
  trebeauty: { name: "Centro Estetico 3 Beauty", kind: "estetica", city: "Thiene" },
  melacerba: { name: "Estetica Melacerba", kind: "estetica", city: "Thiene" },
  nomasvello: { name: "Nomasvello", kind: "estetica", city: "Thiene" },
  fisio: { name: "Fisio Studio", kind: "fisioterapia", city: "Thiene" },
  essentialurbanda: { name: "Essential Urban Day Spa", kind: "estetica", city: "Thiene" },
  robertoemanuelec: { name: "Roberto Emanuele Centrogomme", kind: "gommista", city: "Thiene" },
  matilde: { name: "Estetica Matilde", kind: "estetica", city: "Schio" },
  fusibel: { name: "Estetica Fusibel", kind: "estetica", city: "Schio" },
  mya: { name: "Mya Estetica", kind: "estetica", city: "Schio" },
  fisiosport: { name: "Fisiosport", kind: "fisioterapia", city: "Schio" },
  beautyparadise: { name: "Beauty Paradise", kind: "estetica", city: "Sarcedo" },
  concetta: { name: "Salone Concetta", kind: "parrucchiere", city: "Sarcedo" },
  erika: { name: "Studio Estetico Erika", kind: "estetica", city: "Colceresa" },
  fisiomat: { name: "Fisiomat", kind: "fisioterapia", city: "Villaverla" },
  andreabeautyspa: { name: "Andrea Beauty Spa", kind: "estetica", city: "Marostica" },
  elenapozzan: { name: "Elena Pozzan", kind: "estetica", city: "Marostica" },

  // ---- Altri ----
  opera: { name: "Opera Parrucchiere", kind: "parrucchiere", city: "Schio" },

  // Demo generiche (senza nome di un salone reale)
  estetica:     { name: "Il tuo centro estetico", kind: "estetica",     city: "", generic: true },
  parrucchiere: { name: "Il tuo salone",          kind: "parrucchiere", city: "", generic: true },
  barbiere:     { name: "La tua barberia",        kind: "parrucchiere", menu: "barbiere", city: "", generic: true },
  unghie:       { name: "Il tuo centro unghie",   kind: "estetica",     menu: "unghie",   city: "", generic: true },
  toelettatura: { name: "La tua toelettatura",    kind: "toelettatura", city: "", generic: true },
  fisioterapia: { name: "Il tuo studio",          kind: "fisioterapia", city: "", generic: true },
  tatuaggi:     { name: "Il tuo studio tattoo",   kind: "tatuaggi",     city: "", generic: true },
  gommista:     { name: "La tua officina",        kind: "gommista",     city: "", generic: true }
};
